
name: Deploy PySpark Artifacts to GCS

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'

jobs:
  deploy-to-gcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload PySpark Scripts
        run: |
          gsutil cp scripts/*.py gs://olist-artifacts-prod-lake/scripts/

